
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 99
#define YY_END_OF_BUFFER 100
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[567] =
    {   0,
        0,    0,  100,   98,   95,   96,   97,    1,   11,   12,
        3,    2,    8,    4,   93,   19,   93,   10,    9,   98,
        5,   20,   94,   94,   15,   16,   18,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   13,   14,   95,   93,   93,
       93,    0,    0,   17,    7,    6,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       23,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   44,   94,   94,   94,    0,    0,   93,

        0,   93,    0,   94,   94,   94,   74,   94,   28,   72,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   50,
       94,   94,   75,   94,   94,   94,   38,   37,   94,    0,
       94,   94,   94,   94,   83,   94,   94,   94,   94,   94,
       94,   94,   73,   94,   94,   94,   94,   94,    0,   94,
       94,   94,   94,   94,   93,   93,   93,    0,   94,   94,
       94,   94,   94,   94,   94,   42,   94,   94,   94,   22,
       94,   94,   94,    0,    0,   94,    0,   21,    0,   94,
       94,   94,   94,   94,   43,   94,   94,   94,   94,   94,
       94,   76,   94,   94,   90,   94,   47,    0,   91,   94,

       94,   94,   94,    0,   94,   94,   94,   94,   92,   94,
       94,   51,   94,   94,   94,   49,   94,    0,    0,   94,
        0,   48,    0,   94,   94,   36,   94,   94,    0,   94,
       94,   94,   52,   94,   53,   94,   94,    0,    0,   94,
       94,   94,   94,    0,   94,   94,   94,   78,    0,   94,
       94,   94,   94,   94,    0,    0,   81,    0,    0,   94,
       94,   55,   94,    0,   94,    0,   94,   94,    0,   94,
        0,    0,   61,   94,   94,   59,   94,    0,   94,   94,
       94,    0,    0,   80,    0,   94,   94,    0,   85,   86,
        0,    0,   94,   41,   94,    0,   94,    0,   94,   29,

        0,    0,    0,    0,   94,   94,   94,    0,   94,   94,
       94,    0,    0,    0,    0,   94,   40,    0,    0,    0,
        0,   94,   94,    0,   94,    0,   57,   94,    0,    0,
        0,    0,   88,   89,   94,   94,   94,    0,    0,   94,
       94,    0,    0,    0,    0,    0,    0,    0,   54,   56,
        0,   94,   94,    0,   79,   58,   94,   60,    0,    0,
        0,    0,   84,   94,   27,    0,    0,    0,   94,   94,
        0,    0,    0,    0,    0,    0,    0,    0,   94,   94,
       24,   25,   26,    0,    0,    0,    0,    0,   94,    0,
        0,    0,   94,    0,    0,   32,    0,    0,    0,    0,

        0,   77,   94,   94,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   34,    0,    0,    0,
        0,    0,   94,   94,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   94,   94,    0,    0,   68,    0,    0,    0,    0,
        0,   33,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   45,   35,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   67,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   69,    0,   82,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       70,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   31,    0,    0,    0,    0,
        0,    0,    0,    0,   65,    0,    0,   63,    0,   71,
        0,   39,    0,    0,    0,   46,    0,    0,    0,   87,
        0,    0,    0,    0,   30,    0,    0,    0,    0,    0,
       64,    0,   62,    0,   66,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    5,    1,    1,    1,    6,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   15,   15,   15,   15,   15,   15,   19,   20,   21,
       22,   23,    1,    1,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       25,   26,   24,   24,   24,   24,   24,   24,   24,   24,
       27,    1,   28,   29,   24,    1,   30,   31,   32,   33,

       34,   35,   36,   37,   38,   39,   24,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   49,   50,   51,   52,
       53,   54,   55,    1,   56,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[57] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    2,    1,    2,    2,    2,    2,    1,    1,
        1,    1,    1,    2,    2,    2,    1,    1,    1,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    1,    1
    } ;

static const flex_int16_t yy_base[568] =
    {   0,
        0,    0,  640,  641,   55,  641,  641,  641,  641,  641,
      641,  641,  641,   45,   49,  641,   55,  617,  641,  616,
      641,  615,    0,  610,  641,  641,  641,  602,   26,   32,
       47,   44,  581,   45,  584,   53,   62,  589,   48,   68,
      597,   61,   72,  588,  591,  641,  641,   77,  104,  110,
      114,  124,  134,  641,  641,  641,    0,  624,  597,  112,
      578,  592,  580,  583,  570,  572,  582,  589,  587,  583,
       95,  575,  573,  578,   38,   55,  571,  579,  113,  563,
      577,  561,  562,  564,  566,   78,  115,  557,  562,  557,
      127,  549,  560,  596,  550,  126,  551,  150,  154,  159,

      163,  167,  553,  552,  551,  546,    0,  550,    0,    0,
      545,  557,  546,  556,  542,  541,  544,  537,  550,    0,
      539,  548,    0,  577,  576,  539,  574,    0,  543,  533,
      531,  544,  539,  528,  541,  522,  516,  536,  525,  536,
      531,  516,    0,  515,   89,  518,  521,  526,  509,  524,
      523,  506,  525,  505,  171,  175,  179,  507,  504,  502,
      512,  514,  514,  514,  506,    0,  512,  506,  495,    0,
      496,  494,  510,  496,  495,  507,  497,  488,  485,  490,
      496,  485,  481,  489,    0,  524,  489,  478,  487,  476,
      485,    0,  474,  487,    0,  477,  507,  488,    0,  471,

      486,  480,  484,  479,  474,  463,  468,  474,    0,  504,
      464,    0,  473,  467,  454,    0,  457,  469,  468,  469,
      450,    0,  450,  457,  453,    0,  447,  454,  450,  445,
      487,  448,    0,  447,    0,  484,  441,  160,  440,  437,
      438,  449,  442,  449,  430,  449,  429,    0,  156,  429,
      472,  427,  444,  469,  438,  437,    0,  429,  425,  415,
      425,    0,  432,  432,  426,  420,  429,  425,  410,  455,
      416,  427,  641,  426,  417,    0,  416,  410,  418,  403,
      407,  403,  400,    0,   69,  394,  406,  413,  641,  641,
      400,  394,  159,    0,  402,  407,  397,  165,  405,    0,

      408,  165,  387,  390,  397,  404,  379,  390,  427,  392,
      380,  395,  393,  386,  391,  420,  419,  379,  374,  372,
      376,  375,  374,  412,  373,  379,  641,  367,  366,  368,
      170,  376,  641,  641,  367,  360,  373,  373,  169,  362,
      357,  369,  358,  358,  370,  355,  368,  355,  641,  641,
      363,  354,  346,  201,    0,  641,  389,  641,  359,  359,
      350,  348,    0,  354,    0,  349,  340,  337,  342,  379,
      336,  334,  329,  347,  332,  341,  328,  341,  336,  330,
      641,  641,  641,  338,  337,  340,  316,  338,  363,  318,
      332,  330,  359,  169,  315,  641,  317,  323,  325,  322,

      319,  641,  326,  311,  307,  313,  306,  309,  312,  305,
      310,  313,  302,  301,  304,  309,  641,  304,  311,  308,
      293,  296,  297,  302,  287,  330,  300,  289,  289,  287,
      286,  282,  280,  296,  282,  294,  279,  291,  278,  286,
      270,  314,  313,  278,  285,  641,  273,  280,  272,  269,
      263,  641,  261,  257,  275,  272,  267,  262,  267,  259,
      269,  270,  258,  262,  259,  262,  242,  641,  641,  257,
      249,  255,  244,  250,  256,  258,  238,  252,  249,  254,
      247,  252,  235,  238,  232,  240,  247,  641,  238,  237,
      226,  226,  230,  235,  222,  223,  228,  641,  224,  641,

      222,  234,  216,  215,  224,  257,  212,  213,  220,  223,
      641,  215,  221,  216,  200,  214,  208,  215,  215,  214,
      204,  210,  207,  197,  203,  641,  199,  199,  200,  193,
      202,  195,  206,  205,  641,  196,  191,  641,  189,  641,
      201,  641,  182,  189,  180,  641,  176,  178,  187,  641,
      171,  179,  184,  178,  641,  182,  171,  163,  158,  118,
      641,  113,  641,   77,  641,  641,   80
    } ;

static const flex_int16_t yy_def[568] =
    {   0,
      566,    1,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  567,  567,  566,  566,  566,  567,  567,  567,
      567,  567,  567,  567,  567,  567,  567,  567,  567,  567,
      567,  567,  567,  567,  567,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  567,  567,  567,  567,
      567,  567,  567,  567,  567,  567,  567,  567,  567,  567,
      567,  567,  567,  567,  567,  567,  567,  567,  567,  567,
      567,  567,  567,  567,  567,  567,  567,  567,  567,  567,
      567,  567,  567,  567,  567,  567,  567,  566,  566,  566,

      566,  566,  566,  567,  567,  567,  567,  567,  567,  567,
      567,  567,  567,  567,  567,  567,  567,  567,  567,  567,
      567,  567,  567,  567,  567,  567,  567,  567,  567,  566,
      567,  567,  567,  567,  567,  567,  567,  567,  567,  567,
      567,  567,  567,  567,  567,  567,  567,  567,  566,  567,
      567,  567,  567,  567,  566,  566,  566,  566,  567,  567,
      567,  567,  567,  567,  567,  567,  567,  567,  567,  567,
      567,  567,  567,  566,  566,  567,  566,  567,  566,  567,
      567,  567,  567,  567,  567,  567,  567,  567,  567,  567,
      567,  567,  567,  567,  567,  567,  567,  566,  567,  567,

      567,  567,  567,  566,  567,  567,  567,  567,  567,  567,
      567,  567,  567,  567,  567,  567,  567,  566,  566,  567,
      566,  567,  566,  567,  567,  567,  567,  567,  566,  567,
      567,  567,  567,  567,  567,  567,  567,  566,  566,  567,
      567,  567,  567,  566,  567,  567,  567,  567,  566,  567,
      567,  567,  567,  567,  566,  566,  567,  566,  566,  567,
      567,  567,  567,  566,  567,  566,  567,  567,  566,  567,
      566,  566,  566,  567,  567,  567,  567,  566,  567,  567,
      567,  566,  566,  567,  566,  567,  567,  566,  566,  566,
      566,  566,  567,  567,  567,  566,  567,  566,  567,  567,

      566,  566,  566,  566,  567,  567,  567,  566,  567,  567,
      567,  566,  566,  566,  566,  567,  567,  566,  566,  566,
      566,  567,  567,  566,  567,  566,  566,  567,  566,  566,
      566,  566,  566,  566,  567,  567,  567,  566,  566,  567,
      567,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  567,  567,  566,  567,  566,  567,  566,  566,  566,
      566,  566,  567,  567,  567,  566,  566,  566,  567,  567,
      566,  566,  566,  566,  566,  566,  566,  566,  567,  567,
      566,  566,  566,  566,  566,  566,  566,  566,  567,  566,
      566,  566,  567,  566,  566,  566,  566,  566,  566,  566,

      566,  566,  567,  567,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  567,  567,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  567,  567,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,

      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,    0,  566
    } ;

static const flex_int16_t yy_nxt[698] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   17,   17,   17,   18,   19,
       20,   21,   22,   23,   24,   23,   25,   26,   27,   28,
       23,   29,   23,   30,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   23,   41,   42,   43,   44,   45,
       23,   23,   23,   23,   46,   47,   48,   49,   48,   50,
       50,   50,   50,   51,   51,   51,   51,   49,   60,   50,
       50,   50,   50,   62,   61,  124,   64,   70,   48,   80,
       48,   57,   52,   63,   65,   66,   71,  125,   53,   67,
       73,   76,   68,   81,   88,   74,   82,   83,   89,   77,

       75,   92,  126,  314,   78,   90,  127,   84,   91,   93,
       85,  138,   94,   86,  315,  139,  130,   95,   51,   51,
       51,   51,   49,  565,   50,   50,   50,   50,   51,   51,
       51,   51,  118,   98,  193,   99,  194,   52,  100,  100,
      100,  100,  119,   53,  120,  101,  564,   52,  102,  102,
      102,  102,  105,  106,  131,  140,  145,  151,  107,  563,
      146,  141,  321,  152,  155,  155,  155,  155,  156,  156,
      156,  156,  153,  100,  100,  100,  100,  157,  157,  157,
      157,  102,  102,  102,  102,  155,  155,  155,  155,  156,
      156,  156,  156,  157,  157,  157,  157,  271,  282,  326,

      322,  562,  283,  415,  561,  330,  327,  360,  331,  272,
      332,  367,  361,  560,  416,  368,  381,  382,  383,  559,
      558,  557,  556,  555,  554,  553,  552,  551,  550,  549,
      548,  547,  546,  545,  544,  543,  542,  541,  540,  539,
      538,  537,  536,  535,  534,  533,  532,  531,  530,  529,
      528,  527,  526,  525,  524,  523,  522,  521,  520,  519,
      518,  517,  516,  515,  514,  513,  512,  511,  510,  509,
      508,  507,  506,  505,  504,  503,  502,  501,  500,  499,
      498,  497,  496,  495,  494,  493,  492,  491,  490,  489,
      488,  487,  486,  485,  484,  483,  482,  481,  480,  479,

      478,  477,  476,  475,  474,  473,  472,  471,  470,  469,
      468,  467,  466,  465,  464,  463,  462,  461,  460,  459,
      458,  457,  456,  455,  454,  453,  452,  451,  450,  449,
      448,  447,  446,  445,  444,  443,  442,  441,  440,  439,
      438,  437,  436,  435,  434,  433,  432,  431,  430,  429,
      428,  427,  426,  425,  424,  423,  422,  421,  420,  419,
      418,  417,  414,  413,  412,  411,  410,  409,  408,  407,
      406,  405,  404,  403,  402,  401,  400,  399,  398,  397,
      396,  395,  394,  393,  392,  391,  390,  389,  388,  387,
      386,  385,  384,  380,  379,  378,  377,  376,  375,  374,

      373,  372,  371,  370,  369,  366,  365,  364,  363,  362,
      359,  358,  357,  356,  355,  354,  353,  352,  351,  350,
      349,  348,  347,  346,  345,  344,  343,  342,  341,  340,
      339,  338,  337,  336,  335,  334,  333,  329,  328,  325,
      324,  323,  320,  319,  318,  317,  316,  313,  312,  311,
      310,  309,  308,  307,  306,  305,  304,  303,  302,  301,
      300,  299,  298,  297,  296,  295,  294,  293,  292,  291,
      290,  289,  288,  287,  286,  285,  284,  281,  280,  279,
      278,  277,  276,  275,  274,  273,  270,  269,  268,  267,
      266,  265,  264,  263,  262,  261,  260,  259,  258,  257,

      256,  255,  254,  253,  252,  251,  250,  249,  248,  247,
      246,  245,  244,  243,  242,  241,  240,  239,  238,  237,
      236,  235,  234,  233,  232,  231,  230,  229,  228,  227,
      226,  225,  224,  223,  222,  221,  220,  219,  218,  217,
      216,  215,  214,  213,  212,  211,  210,  209,  208,  207,
      206,  205,  204,  203,  202,  201,  200,  199,  198,  197,
      196,  195,  192,  191,  190,  189,  188,  187,  186,  185,
      184,  183,  182,  181,  180,  179,  178,  177,  176,  175,
      174,  173,  172,  171,  170,  169,  168,  167,  166,  165,
      164,  163,  162,  161,  160,  159,  158,  154,  150,  149,

      148,  147,  144,  143,  142,  137,  136,  135,  134,  133,
      132,  129,  128,  123,  122,  121,  117,  116,  115,  114,
      113,  112,  111,  110,  109,  108,  104,  103,   97,   96,
       87,   79,   72,   69,   59,   58,   56,   55,   54,  566,
        3,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566

    } ;

static const flex_int16_t yy_chk[698] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    5,   14,    5,   14,
       14,   14,   14,   15,   15,   15,   15,   17,   29,   17,
       17,   17,   17,   30,   29,   75,   31,   34,   48,   39,
       48,  567,   15,   30,   31,   32,   34,   75,   17,   32,
       36,   37,   32,   39,   42,   36,   39,   40,   42,   37,

       36,   43,   76,  285,   37,   42,   76,   40,   42,   43,
       40,   86,   43,   40,  285,   86,   79,   43,   49,   49,
       49,   49,   50,  564,   50,   50,   50,   50,   51,   51,
       51,   51,   71,   52,  145,   52,  145,   49,   52,   52,
       52,   52,   71,   50,   71,   53,  562,   51,   53,   53,
       53,   53,   60,   60,   79,   87,   91,   96,   60,  560,
       91,   87,  293,   96,   98,   98,   98,   98,   99,   99,
       99,   99,   96,  100,  100,  100,  100,  101,  101,  101,
      101,  102,  102,  102,  102,  155,  155,  155,  155,  156,
      156,  156,  156,  157,  157,  157,  157,  238,  249,  298,

      293,  559,  249,  394,  558,  302,  298,  331,  302,  238,
      302,  339,  331,  557,  394,  339,  354,  354,  354,  556,
      554,  553,  552,  551,  549,  548,  547,  545,  544,  543,
      541,  539,  537,  536,  534,  533,  532,  531,  530,  529,
      528,  527,  525,  524,  523,  522,  521,  520,  519,  518,
      517,  516,  515,  514,  513,  512,  510,  509,  508,  507,
      506,  505,  504,  503,  502,  501,  499,  497,  496,  495,
      494,  493,  492,  491,  490,  489,  487,  486,  485,  484,
      483,  482,  481,  480,  479,  478,  477,  476,  475,  474,
      473,  472,  471,  470,  467,  466,  465,  464,  463,  462,

      461,  460,  459,  458,  457,  456,  455,  454,  453,  451,
      450,  449,  448,  447,  445,  444,  443,  442,  441,  440,
      439,  438,  437,  436,  435,  434,  433,  432,  431,  430,
      429,  428,  427,  426,  425,  424,  423,  422,  421,  420,
      419,  418,  416,  415,  414,  413,  412,  411,  410,  409,
      408,  407,  406,  405,  404,  403,  401,  400,  399,  398,
      397,  395,  393,  392,  391,  390,  389,  388,  387,  386,
      385,  384,  380,  379,  378,  377,  376,  375,  374,  373,
      372,  371,  370,  369,  368,  367,  366,  364,  362,  361,
      360,  359,  357,  353,  352,  351,  348,  347,  346,  345,

      344,  343,  342,  341,  340,  338,  337,  336,  335,  332,
      330,  329,  328,  326,  325,  324,  323,  322,  321,  320,
      319,  318,  317,  316,  315,  314,  313,  312,  311,  310,
      309,  308,  307,  306,  305,  304,  303,  301,  299,  297,
      296,  295,  292,  291,  288,  287,  286,  283,  282,  281,
      280,  279,  278,  277,  275,  274,  272,  271,  270,  269,
      268,  267,  266,  265,  264,  263,  261,  260,  259,  258,
      256,  255,  254,  253,  252,  251,  250,  247,  246,  245,
      244,  243,  242,  241,  240,  239,  237,  236,  234,  232,
      231,  230,  229,  228,  227,  225,  224,  223,  221,  220,

      219,  218,  217,  215,  214,  213,  211,  210,  208,  207,
      206,  205,  204,  203,  202,  201,  200,  198,  197,  196,
      194,  193,  191,  190,  189,  188,  187,  186,  184,  183,
      182,  181,  180,  179,  178,  177,  176,  175,  174,  173,
      172,  171,  169,  168,  167,  165,  164,  163,  162,  161,
      160,  159,  158,  154,  153,  152,  151,  150,  149,  148,
      147,  146,  144,  142,  141,  140,  139,  138,  137,  136,
      135,  134,  133,  132,  131,  130,  129,  127,  126,  125,
      124,  122,  121,  119,  118,  117,  116,  115,  114,  113,
      112,  111,  108,  106,  105,  104,  103,   97,   95,   94,

       93,   92,   90,   89,   88,   85,   84,   83,   82,   81,
       80,   78,   77,   74,   73,   72,   70,   69,   68,   67,
       66,   65,   64,   63,   62,   61,   59,   58,   45,   44,
       41,   38,   35,   33,   28,   24,   22,   20,   18,    3,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "modelLexer.l"
#line 2 "modelLexer.l"
/*---
  Flow*: A Verification Tool for Cyber-Physical Systems.
  Authors: Xin Chen, Sriram Sankaranarayanan, and Erika Abraham.
  Email: Xin Chen <chenxin415@gmail.com> if you have questions or comments.

  The code is released as is under the GNU General Public License (GPL).
---*/

#include "modelParser.h"
#include "modelParser.tab.h"
#line 791 "lex.yy.c"
#line 792 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 23 "modelLexer.l"

#line 1011 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 567 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 641 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 24 "modelLexer.l"
{ return '\'';}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 25 "modelLexer.l"
{return '+';}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 26 "modelLexer.l"
{return '*';}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 27 "modelLexer.l"
{return '-';}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 28 "modelLexer.l"
{return EQ;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 29 "modelLexer.l"
{return GEQ;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 30 "modelLexer.l"
{return LEQ;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 31 "modelLexer.l"
{return ',';}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 32 "modelLexer.l"
{return ';';}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 33 "modelLexer.l"
{return ':';}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 34 "modelLexer.l"
{return '(';}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 35 "modelLexer.l"
{return ')';}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 36 "modelLexer.l"
{return '{';}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 37 "modelLexer.l"
{return '}';}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 38 "modelLexer.l"
{return '[';}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 39 "modelLexer.l"
{return ']';}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 40 "modelLexer.l"
{return ASSIGN;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 41 "modelLexer.l"
{return '^';}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 42 "modelLexer.l"
{return '/';}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 43 "modelLexer.l"
{return '>';}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 44 "modelLexer.l"
{return MODE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 45 "modelLexer.l"
{return INIT;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 46 "modelLexer.l"
{return BELONGSTO;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 47 "modelLexer.l"
{return POLYODE1;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 48 "modelLexer.l"
{return POLYODE2;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 49 "modelLexer.l"
{return POLYODE3;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 50 "modelLexer.l"
{return VISUALIZE;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 51 "modelLexer.l"
{return END;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 52 "modelLexer.l"
{return SETTING;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 53 "modelLexer.l"
{return CONTINUOUS;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 54 "modelLexer.l"
{return HYBRID;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 55 "modelLexer.l"
{return FIXEDST;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 56 "modelLexer.l"
{return ADAPTIVEST;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 57 "modelLexer.l"
{return FIXEDORD;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 58 "modelLexer.l"
{return ADAPTIVEORD;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 59 "modelLexer.l"
{return ORDER;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 60 "modelLexer.l"
{return MIN;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 61 "modelLexer.l"
{return MAX;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 62 "modelLexer.l"
{return REMEST;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 63 "modelLexer.l"
{return INTERVAL;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 64 "modelLexer.l"
{return OCTAGON;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 65 "modelLexer.l"
{return GRID;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 66 "modelLexer.l"
{return PLOT;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 67 "modelLexer.l"
{return TM;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 68 "modelLexer.l"
{return QRPRECOND;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 69 "modelLexer.l"
{return IDPRECOND;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 70 "modelLexer.l"
{return TIME;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 71 "modelLexer.l"
{return MODES;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 72 "modelLexer.l"
{return JUMPS;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 73 "modelLexer.l"
{return INV;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 74 "modelLexer.l"
{return GUARD;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 75 "modelLexer.l"
{return RESET;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 76 "modelLexer.l"
{return START;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 77 "modelLexer.l"
{return MAXJMPS;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 78 "modelLexer.l"
{return OUTPUT;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 79 "modelLexer.l"
{return NOOUTPUT;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 80 "modelLexer.l"
{return PRINTON;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 81 "modelLexer.l"
{return PRINTOFF;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 82 "modelLexer.l"
{return UNSAFESET;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 83 "modelLexer.l"
{return STATEVAR;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 84 "modelLexer.l"
{return TMVAR;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 85 "modelLexer.l"
{return PARAAGGREG;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 86 "modelLexer.l"
{return INTAGGREG;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 87 "modelLexer.l"
{return TMAGGREG;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 88 "modelLexer.l"
{return CONTINUOUSFLOW;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 89 "modelLexer.l"
{return LINEARCONTINUOUSFLOW;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 90 "modelLexer.l"
{return HYBRIDFLOW;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 91 "modelLexer.l"
{return TAYLOR_PICARD;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 92 "modelLexer.l"
{return TAYLOR_REMAINDER;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 93 "modelLexer.l"
{return TAYLOR_POLYNOMIAL;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 94 "modelLexer.l"
{return NONPOLY_CENTER;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 95 "modelLexer.l"
{return EXP;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 96 "modelLexer.l"
{return SIN;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 97 "modelLexer.l"
{return COS;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 98 "modelLexer.l"
{return LOG;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 99 "modelLexer.l"
{return SQRT;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 100 "modelLexer.l"
{return NPODE_TAYLOR;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 101 "modelLexer.l"
{return CUTOFF;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 102 "modelLexer.l"
{return PRECISION;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 103 "modelLexer.l"
{return GNUPLOT;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 104 "modelLexer.l"
{return MATLAB;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 105 "modelLexer.l"
{return COMPUTATIONPATHS;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 106 "modelLexer.l"
{return PAR;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 107 "modelLexer.l"
{return UNC;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 108 "modelLexer.l"
{return LTI_ODE;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 109 "modelLexer.l"
{return LTV_ODE;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 110 "modelLexer.l"
{return UNIVARIATE_POLY;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 111 "modelLexer.l"
{return TIME_INV;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 112 "modelLexer.l"
{return TIME_VAR;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 113 "modelLexer.l"
{return STEP;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 114 "modelLexer.l"
{return TRUE;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 115 "modelLexer.l"
{return FALSE;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 120 "modelLexer.l"
{ yylval.dblVal = atof( (char *)yytext ); return NUM; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 122 "modelLexer.l"
{ yylval.identifier = new std::string(yytext); return IDENT; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 124 "modelLexer.l"

	YY_BREAK
case 96:
/* rule 96 can match eol */
YY_RULE_SETUP
#line 126 "modelLexer.l"
{ lineNum++; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 128 "modelLexer.l"
{	/* Comment line */
	int c;
	c = yyinput();
	while(c!='\n' && c!=EOF)
	{
		c = yyinput();
	}
	
	if(c == '\n')
	{
		++lineNum;
	}
}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 142 "modelLexer.l"
{ printf("Unknown Character in line %d : %s -- Ignored\n", lineNum, yytext); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 144 "modelLexer.l"
ECHO;
	YY_BREAK
#line 1576 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 567 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 567 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 566);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 144 "modelLexer.l"



int yywrap()
{
	return 1;
}

void parseODE()
{
	int length = parseSetting.strODE.size();
	char *strODE = new char[length+5];

	sprintf(strODE, "%s", parseSetting.strODE.c_str());

	YY_BUFFER_STATE current = YY_CURRENT_BUFFER;

	YY_BUFFER_STATE yybs = yy_scan_string(strODE);

	yy_switch_to_buffer(yybs);
	yyparse();
    yy_delete_buffer(yybs);

	yy_switch_to_buffer(current);

	delete [] strODE;
}

void parseUnivariatePolynomial(const std::string & strPolynomial)
{
	int length = strPolynomial.size();
	char *strInput = new char[length+5];

	sprintf(strInput, "%s", strPolynomial.c_str());

	YY_BUFFER_STATE current = YY_CURRENT_BUFFER;

	YY_BUFFER_STATE yybs = yy_scan_string(strInput);

	yy_switch_to_buffer(yybs);
	yyparse();
    yy_delete_buffer(yybs);

	yy_switch_to_buffer(current);

	delete [] strInput;
}

